name: Rust build & fmt 

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3.2.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          $CARGO_HOME/bin/
          $CARGO_HOME/registry/index/
          $CARGO_HOME/registry/cache/
          $CARGO_HOME/git/db/

        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        # The chunk size used to split up large files during upload, in bytes
        # upload-chunk-size: # optional
        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
        # enableCrossOsArchive: # optional, default is false
        # Fail the workflow if cache entry is not found
        # fail-on-cache-miss: # optional, default is false
    - name: Cargo Fmt
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
